"""Update Term schema

Revision ID: c5ac61fc4e9d
Revises: 
Create Date: 2025-06-05 12:26:48.339678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ac61fc4e9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
